#!/bin/bash
COST_PINEAPPLE=50
COST_BANANA=4
COST_WATERMELON=23
COST_BASKET=1
TOTAL=$(($COST_PINEAPPLE+2*$COST_BANANA+3*$COST_WATERMELON+$COST_BASKET))
echo "Total Cost is $TOTAL"

echo -e "----------OPERATORS---------------"

STRING="this is a string"
echo ${#STRING}            # 16
SUBSTRING="hat"
expr index "$STRING" "$SUBSTRING"     # 1 is the position of the first 't' in $STRING

POS=1
LEN=3
echo ${STRING:$POS:$LEN}   # his
echo ${STRING:1}           # $STRING contents without leading character
echo ${STRING:12}          # 

# Code to extract the First name from the data record
DATARECORD="last=Clifford,first=Johnny Boy,state=CA"
COMMA1=`expr index "$DATARECORD" ','`  # 14 position of first comma
CHOP1FIELD=${DATARECORD:$COMMA1}       #
COMMA2=`expr index "$CHOP1FIELD" ','`
LENGTH=`expr $COMMA2 - 6 - 1`
FIRSTNAME=${CHOP1FIELD:6:$LENGTH}      # Johnny Boy
echo $FIRSTNAME

echo -e "----------REPLACEMENT---------------"

STRING="to be or not to be"
echo ${STRING[@]/be/eat}        # to eat or not to be
echo ${STRING[@]//be/eat}        # to eat or not to eat
echo ${STRING[@]// not/}        # to be or to be
echo ${STRING[@]/#to be/eat now}    # eat now or not to be
echo ${STRING[@]/%be/eat}        # to be or not to eat
echo ${STRING[@]/%be/be on $(date +%Y-%m-%d)}    # to be or not to be on 2012-06-14





