#!/bin/bash

function STWORZ_PLIKI {
  a=$1
  
  if [ ! -e pliki ]; then
    mkdir pliki
  fi


  ITER=1
  while [ $ITER -le $a ]; do
    touch pliki/$ITER
    echo "Stworzono plik nr $ITER"
    ITER=$(($ITER + 1))
  done
}

STWORZ_PLIKI 100
